spring.application.name=quantity-measurement-app

# ==========================
# H2 DATABASE CONFIGURATION
# ==========================
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# H2 CONSOLE
# ==========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# SQL INITIALIZATION
# ==========================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ==========================
# LOGGING
# ==========================
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.security=DEBUG

# ==========================
# ACTUATOR
# ==========================
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

# ==========================
# SWAGGER
# ==========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==========================
# GOOGLE OAUTH2
# ==========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# ==========================
# JWT
# ==========================
app.jwt.secret=MyVeryStrongSecretKeyForJwtTokenAuthentication123456

app.jwt.expiration=86400000